### ISSUE TITLE
crash on attempt to display

### ISSUE THREAD

**Issue by SunilPaul174** [redpenguinyt/display3d#3] opened 2024-04-05 07:54 UTC
When attempting to load the included blåhaj model, it crashes

1. Run the command `RUST_BACKTRACE=full display3d blahaj.obj -t 0,0,5.5`

**Expected behavior**
Spinning blåhaj in terminal

Parsed model for a total of 270 faces. Displaying...
thread 'main' panicked at /home/overlord/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gemini-engine-0.14.1/src/elements/view/pixel/vec2d.rs:55:1:
attempt to calculate the remainder with a divisor of zero
stack backtrace:
   0:     0x5bed1aab72a5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9a7c8ebfe0e5a9ea
   1:     0x5bed1aadc90b - core::fmt::write::hafeb62294a20d279
   2:     0x5bed1aab4f9f - std::io::Write::write_fmt::h83162bfc67f19d63
   3:     0x5bed1aab707e - std::sys_common::backtrace::print::he94870e87e3768e8
   4:     0x5bed1aab8669 - std::panicking::default_hook::{{closure}}::hd193b85d1d659c30
   5:     0x5bed1aab83d3 - std::panicking::default_hook::h6de7d4d748c8b263
   6:     0x5bed1aab8b04 - std::panicking::rust_panic_with_hook::ha4c10d4e371025d4
   7:     0x5bed1aab89ad - std::panicking::begin_panic_handler::{{closure}}::h8d8b80cfb6d2af9a
   8:     0x5bed1aab7769 - std::sys_common::backtrace::__rust_end_short_backtrace::hedf50fb5defff019
   9:     0x5bed1aab8717 - rust_begin_unwind
  10:     0x5bed1aa0d4b6 - core::panicking::panic_fmt::hde3e2c796a3a5416
  11:     0x5bed1aa0d55f - core::panicking::panic::h150613825d1ad83d
  12:     0x5bed1aa43b3d - <gemini_engine::elements::view::pixel::vec2d::Vec2D as core::ops::arith::Rem>::rem::h105758bb6e550970
  13:     0x5bed1aa4072e - gemini_engine::elements::view::View::plot::h00e51d47e412cf25
  14:     0x5bed1aa28ffc - gemini_engine::gameloop::with_root::MainLoopRoot::main_loop::h4cb9ebb27c17e918
  15:     0x5bed1aa232eb - display3d::main::h5f46ddb35485eee6
  16:     0x5bed1aa2d3c3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9852b8bbb3dab5bc
  17:     0x5bed1aa2f829 - std::rt::lang_start::{{closure}}::h29201e19d310d1d1
  18:     0x5bed1aab0bd1 - std::rt::lang_start_internal::h983d5a44e7093a3b
  19:     0x5bed1aa23535 - main
  20:     0x7135bd4cdcd0 - <unknown>
  21:     0x7135bd4cdd8a - __libc_start_main
  22:     0x5bed1aa0da65 - _start
  23:                0x0 - <unknown>

` ╭─  Arch Linux x86_64
 ├─  6.8.2-zen2-1-zen
 ├─  overlord
 ├─󰏗  1883 (pacman)
 ╰─  zsh 5.9

 ╭─  Plasma 6.0.3
 ├─  WezTerm

 ╭─  HP Laptop 15s-fq1xxx
 ├─󰍛  Intel i7-1065G7 (8) @ 3.9GHz [73.0°on]
 ├─󰍹  Intel Iris Plus Graphics G7
 ├─  1920x1080
 ├─  4.33GiB / 11.38GiB (38%)
 ├─  (/)  262G / 299G (88%)
 ╰─󰄉  14 hours, 36 mins

                           `

No blåhaj

**Comment by renpenguin** [comment] 2024-04-12 14:28
running the same command results in a properly rendered blahaj on v0.1.7. what version of display3d do you have installed? (you can use `display3d -V` to check). Is the blahaj.obj unmodified, directly downloaded from this github repo's resources directory? or has it been modified in some way?

**Comment by SunilPaul174** [comment] 2024-04-12 14:49
Just built my own pc! Issue still persists tho

Cloned the repository, but installed from crates.io with `cargo install display3d`

The version is 0.1.13

`❯ RUST_BACKTRACE=full display3d blahaj.obj -t 0,0,5.5
Parsed model for a total of 270 faces. Displaying...
thread 'main' panicked at /home/overlord/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gemini-engine-0.14.1/src/elements/view/pixel/vec2d.rs:55:1:
attempt to calculate the remainder with a divisor of zero
stack backtrace:
   0:     0x5882f19a3655 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hde32b3d93fa0cbf3
   1:     0x5882f19c813b - core::fmt::write::h69f4c8eb5cc948c5
   2:     0x5882f19a136f - std::io::Write::write_fmt::h21afc042172c5224
   3:     0x5882f19a342e - std::sys_common::backtrace::print::h7143ab543bf3c1ef
   4:     0x5882f19a47b9 - std::panicking::default_hook::{{closure}}::h82692e61db443a49
   5:     0x5882f19a4523 - std::panicking::default_hook::h5a924eb77544409b
   6:     0x5882f19a4c54 - std::panicking::rust_panic_with_hook::h9bbdce2368d99cf6
   7:     0x5882f19a4afd - std::panicking::begin_panic_handler::{{closure}}::hf6aed902f8432225
   8:     0x5882f19a3b19 - std::sys_common::backtrace::__rust_end_short_backtrace::h0662ad52c2ccb753
   9:     0x5882f19a4867 - rust_begin_unwind
  10:     0x5882f18f94f6 - core::panicking::panic_fmt::hd80559742a047b08
  11:     0x5882f18f9b7a - core::panicking::panic_const::panic_const_rem_by_zero::h43ee28ebc4631d96
  12:     0x5882f1930aca - gemini_engine::elements::view::wrapping::Wrapping::handle_bounds::h329e009c982267fb
  13:     0x5882f192c825 - gemini_engine::elements::view::View::plot::h71d07d6127557a0d
  14:     0x5882f1919b2c - gemini_engine::gameloop::with_root::MainLoopRoot::main_loop::h256a4359a266c225
  15:     0x5882f190f47b - display3d::main::h2c03a12ae2cb3de4
  16:     0x5882f19183d3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h17f32173bb380102
  17:     0x5882f1918999 - std::rt::lang_start::{{closure}}::h78a195d31185af2a
  18:     0x5882f199cd08 - std::rt::lang_start_internal::h27c88b75c9a51952
  19:     0x5882f190f6c5 - main
  20:     0x77ad883f1cd0 - <unknown>
  21:     0x77ad883f1d8a - __libc_start_main
  22:     0x5882f18f9ba5 - _start
  23:                0x0 - <unknown>`

**Comment by renpenguin** [comment] 2024-04-12 15:01
oh yeah ok looks like you're getting this error because display3d is detecting your terminal size to be (0,0). i just pushed a new commit, can you reclone the repo and run `RUST_BACKTRACE=full cargo run --release -- blahaj.obj` in the repo's directory?

**Comment by renpenguin** [comment] 2024-04-12 15:06
i was able to reproduce the error by scaling my terminal down to a size smaller than 4 rows, 2 columns

**Comment by SunilPaul174** [comment] 2024-04-12 15:58
result is
`Parsed model for a total of 270 faces. Displaying...
The canvas size contains a 0 (Vec2D(0, -3)), which is invalid
Terminal size: Some(Size { rows: 0, cols: 0 })`
The last two lines repeat infinitely.
I am on KDE Wayland using wezterm currently

**Comment by renpenguin** [comment] 2024-04-19 03:30
hmm, so the termsize crate (https://github.com/softprops/termsize jf you want to create an issue for this there) is returning (0,0) as the terminal size. what does `stty size` output for you?

as far as the issue goes, this is no longer a problem with display3d or gemini-engine, but im curious about the cause of the error in case i can implement a workaround

**Comment by SunilPaul174** [comment] 2024-04-20 06:54
❯ stty size
40 160

❯ cargo run 
rows 40 cols 160

When using the following simple program
`extern crate termsize;

pub fn main() {
  termsize::get().map(|size| {
    println!("rows {} cols {}", size.rows, size.cols)
  });
}`

**Comment by renpenguin** [comment] 2024-04-20 23:28
this is very strange, i'll look further into it

**Comment by renpenguin** [comment] 2024-05-02 18:02
started getting this error myself recently, and discovered that this was a problem where termsize was returning (0,0) when building for release. the termsize crate has been replaced with terminal_size, and everything should now work again! this error is fixed as of v0.1.14

**Closed as completed by renpenguin** 2024-05-02 18:02 UTC
Labels: bug
